### ISSUE TITLE
[bug] Inference: <Issue> llama does not appear to have a file named config.json

### ISSUE THREAD

**Issue by jilianwang-meta** [ShishirPatil/gorilla#111]
**Describe the bug**
bug appear：llama does not appear to have a file named config.json
llama paremeter is from huggingface

**To Reproduce**
1.python3 apply_delta.py  --base-model-path ../model/Llama-2-7b --target-model-path ../model/gorilla-7b-hf-v0 --delta-path ../model/gorilla-7b-hf-delta-v0
2. Error

**Screenshots**

![image](https://github.com/ShishirPatil/gorilla/assets/135222790/297d56ef-4d0c-4758-b47f-33643cd9b71f)

**Comment by cucearda** [comment]
Having the same problem trying to apply delta's on falcon weights

**Comment by ShishirPatil** [comment]
Hey @jilianwang-meta and @cucearda thanks for trying Gorilla! 

The llama models are all based on llama-v1 and NOT llama-v2. So @jilianwang-meta the `--base-model-path ../model/Llama-2-7b` is throwing the error since we need the base model to be llama-v1 and apply delta on top of that. 

For the falcon (and mpt) models we release the weights directly as they are apache 2.0 licensed. Hence, you don't need to apple the delta on falcon weights @cucearda 

Let me know if you have any questions / this doesn't work.
