### ISSUE TITLE
Scene Understading and general response without function calling

### ISSUE THREAD

**Issue by samueleruffino99** [ShishirPatil/gorilla#236]
Hello! Amazing work!

I was wondering whether it is possible to get general response without any function colling with your model. Apparently when I am asking it some general question happens that call some random question instead of replying accordingly or, instead of at least saying that it is not sure on which function to call (or that it hasn't found any reasonable function).
  Moreover, I would like to integrate a scene understanding of a driving scenario. Is it possible to integrate vision models in some way to this model, or do you think that extracting info with an off-the-shelf vision model and feed it to Gorilla model may work? Reasoning on the given input?

Thank you very much!

**Comment by kulnor** [comment]
I just started integrating into a Python app and have the same issue: Is there a way to fail the call if no relevant function is found? Based on the examples I have seen and my initial tests, a function call is always returned, even if the query makes no sense.

**Comment by ShishirPatil** [comment]
Hey @kulnor and @samueleruffino99 as mentioned on discord, this is actually fixed in open-functions v2 and is one of the strengths of the model. Here's an example. 

![image](https://github.com/ShishirPatil/gorilla/assets/30296397/be5a86c5-b4ac-4621-8def-992829faf33e)

Feel free to re-open the issue, if this persists or if you run into any more issues!

**Comment by wangbochao1** [comment]
@ShishirPatil 

I find the same problem with open-functions v2 
https://github.com/ShishirPatil/gorilla/issues/289
