### ISSUE TITLE
idea:  The DB-GPT project is doing something similar.

### ISSUE THREAD

**Issue by csunny** [ShishirPatil/gorilla#24]
Thank you very much for your work. We are also implementing similar functionality through a plugin mechanism in our DB-GPT project.

open source:  https://github.com/csunny/DB-GPT

**Comment by ShishirPatil** [comment]
It's encouraging to hear about your efforts, @csunny and Good Luck!! From what I understand from your documentation, you've initiated the DB-GPT project aiming ".. DB-GPT project to build a complete private large model solution for all database-based scenarios." Our focus at Gorilla 🦍 is slightly different, as we're working towards interacting with extensive APIs. If you're open to a potential collaboration, we'd be more than happy to discuss possibilities and feel free to raise a PR. 

Closing this, since it is not really an issue.
