### ISSUE TITLE
RAFT pdf

### ISSUE THREAD

**Issue by jh941213** [ShishirPatil/gorilla#273]
assets/RAFT.pdf

We demonstrate that our RAG approach trains the model to perform better RAG on the set of documents it is trained on i.e., in-domain. By removing the oracle documents in some instances of the training data, we are compelling the model to memorize domain-knowledge. The training data for RAFT is as follows, and an example training data can be seen in the figure below:

P % of data: Q + D* + D1 + D2 + ... + Dk => A*
1-P % of data: Q + D1 + D2 + ... + Dk => A*

The expression says that the dataset is composed of only confusion data except oracle data, but in the figure, I don't see a picture of training with only confusion data.

**Comment by ShishirPatil** [comment]
Hey @jh941213, Thanks for reaching out and for your keen observation on the training data depiction in the RAFT.pdf.

The figure you're referring to is indeed designed to be illustrative, showcasing the general structure and approach of our training methodology. The key takeaway from the visual should be the conceptual overview it provides rather than a detailed breakdown of every possible training scenario. The equations you've highlighted serve as the definitive guide to understanding how the dataset is structured and utilized throughout the training process.

Hope this helps! Let us know if you have any other questions!
