### ISSUE TITLE
how to test new model on BFCL?

### ISSUE THREAD

**Issue by zhangyingerjelly** [ShishirPatil/gorilla#438]
I need to evaluate a model on BFCL, but it's not listed in the predefined model catalog. Do I have to create a custom model_handler.py file to achieve this, or is there another file that can be used directly to define a new model?

**Comment by CharlieJCJ** [comment]
Hi @zhangyingerjelly, the process of adding a new model is documented in [this section](https://github.com/ShishirPatil/gorilla/tree/main/berkeley-function-call-leaderboard#contributing) of the BFCL README. Let us know if you have more questions. We're happy to discuss this in the Discord channel as well if you're facing issues setting it up. 
<img width="1037" alt="image" src="https://github.com/ShishirPatil/gorilla/assets/55744150/36aef394-429a-4527-acd3-e098d76702d2">
If the model is private, feel free to do step 1-4 in the above screenshot. Thanks!

**Comment by HuanzhiMao** [comment]
Adding on to Charlie's comment. You also need to add the model information in `MODEL_METADATA_MAPPING`([code here](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py#L46)); otherwise the final score table won't generate. 
BTW, if your model outputs in a common format (eg, OpenAI, Claude, etc), you should take a look at all the existing model handlers first; very likely you can re-use one of them.
