### ISSUE TITLE
[bug] Hosted Gorilla: <Issue>

### ISSUE THREAD

**Issue by kobikun** [ShishirPatil/gorilla#445]
On the testing, I did not test with error message.

Error communicating with OpenAI: HTTPConnectionPool(host='luigi.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10584e650>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by The-Saurabh-Rajpoot** [comment]
same i also getting

**Comment by ShishirPatil** [comment]
Thanks for raising this. Acknowledge and I am looking into it. The colab / browser / APIs all use the same end-point. So, this should be consistent across all form-factors.

**Comment by ShishirPatil** [comment]
The campus (UC Berkeley) lost power which led to this, this should now be fixed.

**Comment by belizgunel** [comment]
Hi all, I am still getting `Error: Error communicating with OpenAI: HTTPConnectionPool(host='luigi.millennium.berkeley.edu', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b6cd7707dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))` -- `http://zanino.millennium.berkeley.edu:8000/v1` works, though.

Is there another HTTPConnectionPool one can use for 'gorilla-openfunctions-v2'? @ShishirPatil

**Comment by The-Saurabh-Rajpoot** [comment]
I am also getting
