### ISSUE TITLE
Question about AST evaluation for Java and JavaScript

### ISSUE THREAD

**Issue by lucenzhong** [ShishirPatil/gorilla#477]
https://github.com/ShishirPatil/gorilla/blob/2f39693df9868737e8074091d549b652d446d995/berkeley-function-call-leaderboard/model_handler/gpt_handler.py#L94C1-L109C30
Hello, May I ask why the gpt model with FC do not use `tree-sitter` to do the AST parsing for Java and JavaScript test categorie ?

**Comment by HuanzhiMao** [comment]
Hi @lucenzhong,
GPT models in FC mode don't need to have their result parsed for Java and JavaScript categories, because the model output is in JSON format and all the parameters involved with the Java/JS test are of type `string`, which is JSON compatible. So here, `json.load` is enough to get the result ready to be fed into the evaluation pipeline. The actual parsing part (to turn parameter value from `string` into their 'real' type) for these parameters happens in the checker section([here](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/checker.py#L364-L388)), which involves calling the [Java type converter](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/java_type_converter.py) and the [JS type converter](https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/eval_checker/js_type_converter.py). These two converters both make use of the `tree-sitter`.
Let me know if you have more questions!
