### ISSUE TITLE
[BFCL] Potential bug in calculating accuracy

### ISSUE THREAD

**Issue by XuHwang** [ShishirPatil/gorilla#591]
**Describe the issue**
A clear and concise description of what the issue is.

**What is the issue**
I find the calculation of the simple AST score in the non-live part in v2 is not consistent with that in v1. 

v1: scores of python, java and js are summed with `calculate_weighted_accuracy`

v2: scores of python, java and js are summed with `calculate_unweighted_accuracy`

Maybe the results on the webpage are not so correct. (I guess the results on current webpage are directly calculated with the results on the previous page and the results in the live part, (score_v1+score_v2)/2 .)

**Proposed Changes**

**Additional context**

**Comment by HuanzhiMao** [comment]
Hi @XuHwang,
It is intentional and not a bug. As mentioned in #580, in BFCL V2, we have changed the overall accuracy to be the **unweighted** average of each of the sub-categories.
  - `"exec_simple", "exec_parallel", "exec_multiple", "exec_parallel_multiple", "simple", "irrelevance", "parallel", "multiple", "parallel_multiple", "java", "javascript", "rest", "live_simple", "live_multiple", "live_parallel", "live_parallel_multiple", "live_irrelevance", "live_relevance"` 
 
And so the summary score for python simple, python java and python javascript are also summed **unweighted**.
