### ISSUE TITLE
[BFCL] The handling of prompt formatting in GLM is incorrect.

### ISSUE THREAD

**Issue by zhangch-ss** [ShishirPatil/gorilla#637]
**Describe the issue**
Hi, thanks for your excellent work.
I think there is a bug in the formatted prompt handling of GLM.

**ID datapoint**
https://github.com/zhangch-ss/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/glm.py
`apply_chat_template`

**What is the issue**
This is the result of apply_chat_template, and it seems that the tool descriptions are missing. Additionally, it appears that support for multiple roles is not yet implemented.
`"[gMASK]<sop><|user|>\nI'm playing a dice game and want to calculate my chances. I roll the die 20 times, and I'm trying to figure out the probability of landing on a 6 exactly five times, considering each roll has a one in six chance of being a 6. Could you help me with that?<|assistant|>"`

**Proposed Changes**
It seems that the `apply_chat_template` function needs to be modified to support the mentioned features. If possible, I would be happy to submit a PR to fix it.

**Comment by HuanzhiMao** [comment]
Hi @zhangch-ss,
Thanks for the issue. We also noticed the abnormal behaviour of the GLM model, thus we haven't report its score on the leaderboard. (We can tell it's abnormal because it scores 0 on all the non-live categories (the same as BFCL V1) and it used to score quite a lot on those categories before the release of the live dataset). If you raise the PR, we are happy to review it.

**Comment by zhangch-ss** [comment]
Thanks for your reply, this issue may be the cause of the abnormal behavior of glm, 
This is the evaluation result of non-live categories after fixed.
It looks normal, but GLM seems to be incapable of parallel function calling
![image](https://github.com/user-attachments/assets/5267f003-eff3-4fb7-9e0c-421b2098bebb)
I have submitted a PR.
