### ISSUE TITLE
[bug] Testing Gorilla: <Issue>

### ISSUE THREAD

**Issue by rc9909** [ShishirPatil/gorilla#66]
Exception: Error communicating with OpenAI: HTTPConnectionPool(host='34.132.127.197', port=8000): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7bba974da140>: Failed to establish a new connection: [Errno 111] Connection refused'))
Failed model: gorilla-7b-tf-v0, for prompt: I want to build a robot that can detecting objects in an image

**Comment by ShishirPatil** [comment]
Hey @rc9909 Apologies for that. Our instance was shut down by the cloud provider. It's back up - I migrated the instance with the same IP. I have observed it over the past few mins and we are able to serve requests - so everything should be back up! 

BTW if you run into any issues due to capacity, there is another IP (the primary IP) you can use. Just replace `http://34.132.127.197:8000/v1` with `http://zanino.millennium.berkeley.edu:8000/v1`!
