### ISSUE TITLE
The main differences between the prompt template and the prompt_FC template.

### ISSUE THREAD

**Issue by belief888** [ShishirPatil/gorilla#816]
What are the main differences in details between the prompt template and the prompt_FC template? Please describe specifically.

**Comment by HuanzhiMao** [comment]
Which prompt_FC template are you referring to?

**Comment by belief888** [comment]
What is the fundamental difference between minicpm.py aminicpm_fc.py inoss_model directory?

**Comment by HuanzhiMao** [comment]
minicpm.py is for the model in prompting mode, while minicpm_fc.py is for the model in function calling mode. It's the same logic for ChatGPT or Claude in prompt vs FC mode, except since it's an OSS model, we have to do some special treatment to apply its chat template.

> FC means the model supports native tool use. For example, for gpt in FC mode, it means we supply the function choices in the `tools` section: https://platform.openai.com/docs/guides/function-calling
while gpt in prompt mode just means we are using the model's normal text generation capability; it's also a walk-around for models that's don't natively support tool use: https://platform.openai.com/docs/guides/text-generation/quickstart

**Comment by HuanzhiMao** [comment]
There is also a more detailed explanation in https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/CONTRIBUTING.md
